# Generated by Django 3.2.10 on 2022-04-18 18:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='prof_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
